# Generated by Django 2.2.3 on 2021-04-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='participants',
            fields=[
                ('M1MailId', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='M1MailId')),
                ('M1Name', models.CharField(max_length=30, null=True, verbose_name='M1Name')),
                ('M1College', models.CharField(max_length=30, null=True, verbose_name='M1College')),
                ('M1Phone', models.CharField(max_length=15, null=True, verbose_name='M1Phone')),
                ('M2MailId', models.EmailField(max_length=30, null=True, verbose_name='M2MailId')),
                ('M2Name', models.CharField(max_length=30, null=True, verbose_name='M2Name')),
                ('M2College', models.CharField(max_length=30, null=True, verbose_name='M2College')),
                ('M2Phone', models.CharField(max_length=15, null=True, verbose_name='M2Phone')),
                ('M3MailId', models.EmailField(max_length=30, null=True, verbose_name='M3MailId')),
                ('M3Name', models.CharField(max_length=30, null=True, verbose_name='M3Name')),
                ('M3College', models.CharField(max_length=30, null=True, verbose_name='M3College')),
                ('M3Phone', models.CharField(max_length=15, null=True, verbose_name='M3Phone')),
                ('M4MailId', models.EmailField(max_length=20, null=True, verbose_name='M4MailId')),
                ('M4Name', models.CharField(max_length=30, null=True, verbose_name='M4Name')),
                ('M4College', models.CharField(max_length=30, null=True, verbose_name='M4College')),
                ('M4Phone', models.CharField(max_length=15, null=True, verbose_name='M4Phone')),
            ],
        ),
    ]
